Repository googleapis/python-dms, pull requests merged in 2021-08, with the labels that each got.

#28 feat: bump release level to production/stable
  .repo-metadata.json
  README.rst
  docs/README.rst
  setup.py
Labels: automerge, cla: yes

#32 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: automerge, cla: yes, samples

#34 chore: migrate to main branch
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  docs/conf.py
  owlbot.py
Labels: cla: yes
